language: python
dist: xenial
python:
#  - "2.7"  # sqlite3.enable_load_extension not available
  - "3.5"
  - "3.7"
matrix:
  fast_finish: true

install:
  - pip install -r requirements.txt
  - ( cd niimpy ; curl https://sqlite.org/contrib/download/extension-functions.c?get=25 > sqlite-extension-functions.c ; gcc -lm -shared -fPIC sqlite-extension-functions.c -o sqlite-extension-functions.so )

script:
  - pytest
