name: Docs
on: [push, pull_request]
jobs:
  test:
    name: sphinx build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          cd docs/
          pip install -r requirements.txt
      #- name: setup extension
      - name: sphinx
        run: |
          cd docs
          make clean dirhtml SPHINXOPTS='-W --keep-going'
